### ISSUE TITLE
Package circular import error

### ISSUE THREAD

**Issue by suqi95716aa** [spcl/graph-of-thoughts#10]
Why I quote your demo and got error that "`ImportError: cannot import name 'GraphOfOperations' from partially initialized module 'graph_of_thoughts.operations' (most likely due to a circular import)`"？

I read the partly source code and found after `from graph_of_thoughts import operations`  and controller.py quote this package again.

But I dont know how to fix it

**Comment by suqi95716aa** [comment]
traceback here:
```
Traceback (most recent call last):
  File "xxxxx\demo1.py", line 1, in <module>
    from graph_of_thoughts import operations
  File "xxxxx\graph_of_thoughts\operations\__init__.py", line 2, in <module>
    from .graph_of_operations import GraphOfOperations
  File "xxxxx\graph_of_thoughts\operations\graph_of_operations.py", line 12, in <module>
    from graph_of_thoughts.operations.operations import Operation
  File "xxxxx\graph_of_thoughts\operations\operations.py", line 17, in <module>
    from graph_of_thoughts.controller.abstract_language_model import AbstractLanguageModel
  File "xxxxx\graph_of_thoughts\controller\__init__.py", line 4, in <module>
    from .controller import Controller
  File "xxxxx\graph_of_thoughts\controller\controller.py", line 13, in <module>
    from graph_of_thoughts.operations import GraphOfOperations, Thought
ImportError: cannot import name 'GraphOfOperations' from partially initialized module 'graph_of_thoughts.operations' (most likely due to a circular import) (xxxxx\graph_of_thoughts\operations\__init__.py)

Process finished with exit code 1

```
